// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/bookings/refund": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Starts refund flow and returns refund URL.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Refund a booked ticket",
                "responses": {}
            }
        },
        "/bookings": {
            "post": {
                "description": "Reserves tickets in Redis, applies one discount type, calls Payment Service via gRPC, and returns Payment URL.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Book tickets",
                "responses": {}
            }
        },
        "/tickets": {
            "get": {
                "description": "Get a list of tickets for a specific event from the Slave DB.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tickets"
                ],
                "summary": "Get event tickets",
                "responses": {}
            }
        },
        "/tickets/discounts": {
            "get": {
                "description": "Get early and bundle discounts for a specific event.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discounts"
                ],
                "summary": "Get event discount",
                "responses": {}
            }
        },
        "/user/tickets": {
            "get": {
                "description": "Returns all tickets owned by current user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tickets"
                ],
                "summary": "Get user tickets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http_handler.UserTicketsResponse"
                        }
                    }
                }
            }
        },
        "/user/tickets/transfer": {
            "post": {
                "description": "Publishes ticket transfer request.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "tickets"
                ],
                "summary": "Ticket transfer",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/user/waitlist": {
            "post": {
                "description": "Adds the current user to the waitlist. User must provide email for notifications.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Add user to waitlist",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_transport_http_handler.TicketResponse": {
            "type": "object",
            "properties": {
                "event_id": {
                    "type": "integer",
                    "example": 1024
                },
                "id": {
                    "type": "integer",
                    "example": 5501
                },
                "price": {
                    "type": "integer",
                    "example": 15000
                },
                "row_no": {
                    "type": "integer",
                    "example": 12
                },
                "seat_no": {
                    "type": "integer",
                    "example": 42
                },
                "sector_name": {
                    "type": "string",
                    "example": "Platinum A"
                },
                "status": {
                    "type": "string",
                    "example": "created"
                },
                "venue_id": {
                    "type": "integer",
                    "example": 202
                }
            }
        },
        "internal_transport_http_handler.UserTicketsResponse": {
            "type": "object",
            "properties": {
                "tickets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_transport_http_handler.TicketResponse"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
