// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EventComment struct {
	ID           int64
	EventID      int64
	UserID       int64
	Nick         string
	Text         string
	RatingTenths int64
	CreatedAt    pgtype.Timestamptz
}

type EventRatingAgg struct {
	EventID   int64
	SumTenths int64
	Count     int64
	UpdatedAt pgtype.Timestamptz
}
