// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
WITH ins AS (
  INSERT INTO event_comments (
    event_id,
    user_id,
    nick,
    text,
    rating_tenths
  )
  VALUES ($1, $2, $3, $4, $5)
  RETURNING
    id,
    event_id,
    user_id,
    nick,
    text,
    rating_tenths,
    created_at
),
agg AS (
  INSERT INTO event_rating_agg (
    event_id,
    sum_tenths,
    count,
    updated_at
  )
  SELECT
    event_id,
    rating_tenths,
    1,
    now()
  FROM ins
  ON CONFLICT (event_id) DO UPDATE
    SET
      sum_tenths = event_rating_agg.sum_tenths + EXCLUDED.sum_tenths,
      count      = event_rating_agg.count + 1,
      updated_at = now()
)
SELECT
  id,
  event_id,
  user_id,
  nick,
  text,
  rating_tenths,
  created_at
FROM ins
`

type CreateCommentParams struct {
	EventID      int64
	UserID       int64
	Nick         string
	Text         string
	RatingTenths int64
}

type CreateCommentRow struct {
	ID           int64
	EventID      int64
	UserID       int64
	Nick         string
	Text         string
	RatingTenths int64
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (CreateCommentRow, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.EventID,
		arg.UserID,
		arg.Nick,
		arg.Text,
		arg.RatingTenths,
	)
	var i CreateCommentRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Nick,
		&i.Text,
		&i.RatingTenths,
		&i.CreatedAt,
	)
	return i, err
}

const getRatingByEvent = `-- name: GetRatingByEvent :one
SELECT
  e.event_id,
  (
    CASE
      WHEN COALESCE(a.count, 0) = 0 THEN 0
      ELSE (a.sum_tenths + (a.count / 2)) / a.count
    END
  )::bigint AS avg_tenths,
  COALESCE(a.count, 0)::bigint AS count
FROM (SELECT $1::bigint AS event_id) e
LEFT JOIN event_rating_agg a USING (event_id)
`

type GetRatingByEventRow struct {
	EventID   int64
	AvgTenths int64
	Count     int64
}

func (q *Queries) GetRatingByEvent(ctx context.Context, eventID int64) (GetRatingByEventRow, error) {
	row := q.db.QueryRow(ctx, getRatingByEvent, eventID)
	var i GetRatingByEventRow
	err := row.Scan(&i.EventID, &i.AvgTenths, &i.Count)
	return i, err
}

const listCommentsByEvent = `-- name: ListCommentsByEvent :many
SELECT
  id,
  event_id,
  user_id,
  nick,
  text,
  rating_tenths,
  created_at
FROM event_comments
WHERE event_id = $1::bigint
ORDER BY created_at DESC, id DESC
LIMIT $3::bigint
OFFSET $2::bigint
`

type ListCommentsByEventParams struct {
	EventID    int64
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) ListCommentsByEvent(ctx context.Context, arg ListCommentsByEventParams) ([]EventComment, error) {
	rows, err := q.db.Query(ctx, listCommentsByEvent, arg.EventID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventComment
	for rows.Next() {
		var i EventComment
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.Nick,
			&i.Text,
			&i.RatingTenths,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
