// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "POP",
            "url": "https://github.com/turtlepavlo"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bookings": {
            "post": {
                "description": "Create a temporary reservation in Redis and return payment URL.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Book a ticket",
                "responses": {}
            }
        },
        "/payments/webhook": {
            "post": {
                "description": "Receive payment confirmation from Stripe and finalize booking in DB.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Stripe Webhook",
                "responses": {}
            }
        },
        "/tickets": {
            "get": {
                "description": "Get a list of tickets for a specific event from the Slave DB.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tickets"
                ],
                "summary": "Get event tickets",
                "responses": {}
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Type 'Bearer ' followed by your JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3434",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Event Booking Service API",
	Description:      "API service for event ticket booking. Features include Redis-based ticket locking, Postgres slave-read optimization, and Kafka event streaming for payments.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
